name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - '[FEATURE]'
  - title: '🐛 Bug Fixes'
    labels:
      - '[BUGFIX]'
  - title: '📚 Documentation'
    labels:
      - '[DOCS]'
  - title: '🛠 Tasks'
    labels:
      - '[TASK]'
  - title: '🔐 Security Fixes'
    labels:
      - '[SECURITY]'

version-resolver:
  major:
    labels:
      - '[!!!]'
  minor:
    labels:
      - 'bug'
  patch:
    labels:
      - '[BUGFIX]'
      - '[TASK]'
      - '[DOCS]'
  default: patch

template: |
  ## Changes

  $CHANGES

change-template: '- $TITLE @$AUTHOR (#$NUMBER) - $BODY'