name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Draft release notes
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update CHANGELOG.md
        run: |
          # Update the CHANGELOG.md file with the latest release information
          echo "## $(date +'%Y-%m-%d') - v${{ github.event.release.tag_name }}" >> CHANGELOG.md
          echo >> CHANGELOG.md
          echo "${{ github.event.release.body }}" >> CHANGELOG.md
          echo >> CHANGELOG.md

          # Commit and push the updated CHANGELOG.md back to the repository
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for release v${{ github.event.release.tag_name }}"
          git push
