name: Update CHANGELOG on Release Publish

on:
  release:
    types: [ published ]

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Release Info
        run: |
          echo "## $(date +'%Y-%m-%d') - ${{ github.event.release.tag_name }}" >> CHANGELOG.md
          echo >> CHANGELOG.md
          echo "${{ github.event.release.body }}" >> CHANGELOG.md
          echo >> CHANGELOG.md

      - name: Commit and push CHANGELOG.md
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for release ${{ github.event.release.tag_name }}"
          git push
